apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://gitlab.com/biletado/kustomize.git//overlays/kind?ref=main

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: localhost/reservations-django:local-dev
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/containerPort
        value: 9000
    target:
      group: apps
      version: v1
      kind: Deployment
      name: reservations
